name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Run Tests
      run: |
        python /Security_Camp/manage.py test
